"""add usuario_id to artista

Revision ID: 549acd42cbc8
Revises: c2dd02f5edbc
Create Date: 2026-07-10 11:30:32.751039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549acd42cbc8'
down_revision = 'c2dd02f5edbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
