"""alterando campo de duracao em musica

Revision ID: bcc11c5f84c9
Revises: c44a71b248bb
Create Date: 2026-04-13 20:00:33.765247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc11c5f84c9'
down_revision = 'c44a71b248bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musica', schema=None) as batch_op:
        batch_op.alter_column('duracao',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musica', schema=None) as batch_op:
        batch_op.alter_column('duracao',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
