"""add cascade=all, delete-orphan in musica, album and artista

Revision ID: c2dd02f5edbc
Revises: d4fa78d4a967
Create Date: 2026-04-17 21:49:17.118219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dd02f5edbc'
down_revision = 'd4fa78d4a967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('musica', schema=None) as batch_op:
        batch_op.alter_column('artista_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musica', schema=None) as batch_op:
        batch_op.alter_column('artista_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('avaliacao', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
