"""adding relationship artista-musica

Revision ID: d4fa78d4a967
Revises: 4233f6b2191c
Create Date: 2026-04-15 20:14:08.660656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fa78d4a967'
down_revision = '4233f6b2191c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artista_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'artistas', ['artista_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('musica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artista_id')

    # ### end Alembic commands ###
